<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get" name="search_mini_form">
    <div class="form-search">
        <!--<label for="search"><?//php echo $this->__('Search:') ?></label>-->
        <select id="category_search_field" name="cat" class="dropdown">
            <option value="">Select Category</option>
            <?php foreach ($this->helper('searchautocomplete')->getStoreCategories() as $_category): ?>
            <option value="<?php echo $_category->getId(); ?>"><?php echo $_category->getName();?></option>
            <?php endforeach ?>
        </select>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>"  class="input-text" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete" style="width: 100% !important;left:0px !important;"></div>
        <div id="searching" style="display: none;">
            <p><img src="<?php echo $this->getSkinUrl('images/searching.GIF');?>"/></p>
        </div>
<!--
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
            searchForm.initAutocomplete('<?php echo $this->helper('searchautocomplete')->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
-->
        <script type="text/javascript">
        var categoryId = "";
        jQuery.noConflict();
        jQuery(document).ready(function(){
            
            //<![CDATA[
                var searchForm = new Varien.searchForm('search_mini_form', 'search', 'category_search_field', '<?php echo $this->__('Search entire store here...') ?>');
                searchForm.initAutocomplete('<?php echo $this->helper('searchautocomplete')->getSuggestUrl() ?>', 'search_autocomplete');
            //]]>    
        });
        </script>

    </div>
</form>

<?php echo Mage::helper('searchautocomplete')->getStyle(); ?>
