<div>
<h1>Welcome to the revolution</h1>
<br />
<br />
<h3>Prepare for your exams like never before</h3>
<div>
    <div class="round-image"><span>Image1</span></div>
    <div class="round-image"><span>Image2</span></div>
    <div class="round-image"><span>Image3</span></div>
</div>
<br />
<br />
<h3>STUDENTS FIRST</h3>
<div>Students are our focus. We want to help you get better marks, help impact your future. Come join the revolution.</div>
</div>